/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { IconData, IconSemanticVariant, IconSize } from '@tk-icons/core';
export { IconData, IconSemanticVariant, IconSize } from '@tk-icons/core';
export namespace Components {
  interface TkIcon {
    color?: string;
    /**
     * The icon to render. Obtain icon data from `@tk-icons/core`, e.g. `import addIcon from '@tk-icons/core/icons/outlined/rounded/add'`.
     */
    icon?: IconData;
    /**
     * Accessible label. When provided the icon is exposed to assistive technology as an image with this name; otherwise it is treated as decorative and hidden.
     */
    label?: string;
    /**
     * Sets size for the component.
     * @default 'base'
     */
    size: IconSize;
    /**
     * The semantic color variant of the icon.
     * @default 'primary'
     */
    variant: IconSemanticVariant;
  }
}
declare global {
  interface HTMLTkIconElement extends Components.TkIcon, HTMLStencilElement {}
  var HTMLTkIconElement: {
    prototype: HTMLTkIconElement;
    new (): HTMLTkIconElement;
  };
  interface HTMLElementTagNameMap {
    'tk-icon': HTMLTkIconElement;
  }
}
declare namespace LocalJSX {
  interface TkIcon {
    color?: string;
    /**
     * The icon to render. Obtain icon data from `@tk-icons/core`, e.g. `import addIcon from '@tk-icons/core/icons/outlined/rounded/add'`.
     */
    icon?: IconData;
    /**
     * Accessible label. When provided the icon is exposed to assistive technology as an image with this name; otherwise it is treated as decorative and hidden.
     */
    label?: string;
    /**
     * Sets size for the component.
     * @default 'base'
     */
    size?: IconSize;
    /**
     * The semantic color variant of the icon.
     * @default 'primary'
     */
    variant?: IconSemanticVariant;
  }

  interface TkIconAttributes {
    size: IconSize;
    variant: IconSemanticVariant;
    color: string;
    label: string;
  }

  interface IntrinsicElements {
    'tk-icon': Omit<TkIcon, keyof TkIconAttributes> & {
      [K in keyof TkIcon & keyof TkIconAttributes]?: TkIcon[K];
    } & {
      [K in keyof TkIcon &
        keyof TkIconAttributes as `attr:${K}`]?: TkIconAttributes[K];
    } & {
      [K in keyof TkIcon & keyof TkIconAttributes as `prop:${K}`]?: TkIcon[K];
    };
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'tk-icon': LocalJSX.IntrinsicElements['tk-icon'] &
        JSXBase.HTMLAttributes<HTMLTkIconElement>;
    }
  }
}
