/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { IconData, IconStyle, IconType } from '@tk-icons/core';
export { IconData, IconStyle, IconType } from '@tk-icons/core';
export namespace Components {
  interface TkIcon {
    color?: string;
    icon?: IconData;
    /**
     * @default 'outlined'
     */
    iconStyle: IconStyle;
    /**
     * @default 'rounded'
     */
    iconType: IconType;
    name?: string;
    /**
     * @default 24
     */
    size: number | string;
  }
}
declare global {
  interface HTMLTkIconElement extends Components.TkIcon, HTMLStencilElement {}
  var HTMLTkIconElement: {
    prototype: HTMLTkIconElement;
    new (): HTMLTkIconElement;
  };
  interface HTMLElementTagNameMap {
    'tk-icon': HTMLTkIconElement;
  }
}
declare namespace LocalJSX {
  interface TkIcon {
    color?: string;
    icon?: IconData;
    /**
     * @default 'outlined'
     */
    iconStyle?: IconStyle;
    /**
     * @default 'rounded'
     */
    iconType?: IconType;
    name?: string;
    /**
     * @default 24
     */
    size?: number | string;
  }

  interface TkIconAttributes {
    name: string;
    iconStyle: IconStyle;
    iconType: IconType;
    size: string;
    color: string;
  }

  interface IntrinsicElements {
    'tk-icon': Omit<TkIcon, keyof TkIconAttributes> & {
      [K in keyof TkIcon & keyof TkIconAttributes]?: TkIcon[K];
    } & {
      [K in keyof TkIcon &
        keyof TkIconAttributes as `attr:${K}`]?: TkIconAttributes[K];
    } & {
      [K in keyof TkIcon & keyof TkIconAttributes as `prop:${K}`]?: TkIcon[K];
    };
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'tk-icon': LocalJSX.IntrinsicElements['tk-icon'] &
        JSXBase.HTMLAttributes<HTMLTkIconElement>;
    }
  }
}
