/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconData, IconSemanticVariant, IconSize, IconType } from "@tk-icons/core";
export { IconData, IconSemanticVariant, IconSize, IconType } from "@tk-icons/core";
export namespace Components {
    interface TkIcon {
        "color"?: string;
        /**
          * Indicates whether the filled variant should be used.
          * @default false
         */
        "fill": boolean;
        /**
          * Icon name or full icon data.
         */
        "icon"?: string | IconData;
        /**
          * @default 'rounded'
         */
        "iconType": IconType;
        /**
          * @deprecated Use `icon` instead.
         */
        "name"?: string;
        /**
          * Sets size for the component.
          * @default 'base'
         */
        "size": IconSize;
        /**
          * The semantic color variant of the icon.
          * @default 'primary'
         */
        "variant": IconSemanticVariant;
    }
}
declare global {
    interface HTMLTkIconElement extends Components.TkIcon, HTMLStencilElement {
    }
    var HTMLTkIconElement: {
        prototype: HTMLTkIconElement;
        new (): HTMLTkIconElement;
    };
    interface HTMLElementTagNameMap {
        "tk-icon": HTMLTkIconElement;
    }
}
declare namespace LocalJSX {
    interface TkIcon {
        "color"?: string;
        /**
          * Indicates whether the filled variant should be used.
          * @default false
         */
        "fill"?: boolean;
        /**
          * Icon name or full icon data.
         */
        "icon"?: string | IconData;
        /**
          * @default 'rounded'
         */
        "iconType"?: IconType;
        /**
          * @deprecated Use `icon` instead.
         */
        "name"?: string;
        /**
          * Sets size for the component.
          * @default 'base'
         */
        "size"?: IconSize;
        /**
          * The semantic color variant of the icon.
          * @default 'primary'
         */
        "variant"?: IconSemanticVariant;
    }

    interface TkIconAttributes {
        "icon": string | IconData;
        "name": string;
        "fill": boolean;
        "iconType": IconType;
        "size": IconSize;
        "variant": IconSemanticVariant;
        "color": string;
    }

    interface IntrinsicElements {
        "tk-icon": Omit<TkIcon, keyof TkIconAttributes> & { [K in keyof TkIcon & keyof TkIconAttributes]?: TkIcon[K] } & { [K in keyof TkIcon & keyof TkIconAttributes as `attr:${K}`]?: TkIconAttributes[K] } & { [K in keyof TkIcon & keyof TkIconAttributes as `prop:${K}`]?: TkIcon[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tk-icon": LocalJSX.IntrinsicElements["tk-icon"] & JSXBase.HTMLAttributes<HTMLTkIconElement>;
        }
    }
}
