export type IconStyle = 'outlined' | 'filled';
export type IconType = 'rounded' | 'sharp' | 'bevel' | 'tk';
export type IconVariant = `${IconStyle}/${IconType}`;

export interface IconData {
  name: string;
  style: IconStyle;
  type: IconType;
  variant: IconVariant;
  viewBox: string;
  svg: string;
}

export interface IconMeta {
  name: string;
  category: string;
  tags: string[];
  aliases: string[];
  added: string;
  deprecated: boolean;
  variants: IconVariant[];
}

// <AUTO-GENERATED:UNIONS>
export type IconName = 'arrow-left';
export type CategoryId = 'action' | 'navigation' | 'status';
// </AUTO-GENERATED:UNIONS>
