import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'yaml';
import { ICONS_CORE_SRC, ROOT_DIR, writeGeneratedFile } from './utils';

interface CategoryYaml {
  categories: Array<{
    id: string;
    label: string;
    description: string;
  }>;
}

interface IconYaml {
  category: string;
  tags: string[];
  aliases?: string[];
  added: string;
  deprecated?: boolean;
  variants: string[];
}

interface IconsMetaYaml {
  icons: Record<string, IconYaml>;
}

const categoriesPath = path.join(
  ROOT_DIR,
  'packages/icons-svg/metadata/categories.yaml',
);
const metaPath = path.join(
  ROOT_DIR,
  'packages/icons-svg/metadata/icons.meta.yaml',
);

const categoriesDoc = parse(
  fs.readFileSync(categoriesPath, 'utf8'),
) as CategoryYaml;
const metaDoc = parse(fs.readFileSync(metaPath, 'utf8')) as IconsMetaYaml;

const iconNames = Object.keys(metaDoc.icons).sort();
const categoryIds = categoriesDoc.categories
  .map((category) => category.id)
  .sort();

const iconMetadata = iconNames.map((name) => ({
  name,
  category: metaDoc.icons[name].category,
  tags: metaDoc.icons[name].tags,
  aliases: metaDoc.icons[name].aliases ?? [],
  added: metaDoc.icons[name].added,
  deprecated: Boolean(metaDoc.icons[name].deprecated),
  variants: metaDoc.icons[name].variants,
}));

const metadataContent = `
import type { CategoryId, IconMeta, IconName, IconVariant } from './types';

export const categories = ${JSON.stringify(categoriesDoc.categories, null, 2)} as const;

export const iconMetadata: IconMeta[] = ${JSON.stringify(iconMetadata, null, 2)};

export const iconNames = ${JSON.stringify(iconNames, null, 2)} as const;

const metadataByName: Record<string, IconMeta> = Object.fromEntries(
  iconMetadata.map((icon) => [icon.name, icon])
);

export function getIconMeta(name: string): IconMeta | undefined {
  return metadataByName[name];
}

export function getIconsByVariant(variant: IconVariant): IconMeta[] {
  return iconMetadata.filter((icon) => icon.variants.includes(variant));
}

export function getIconsByCategory(category: CategoryId | string): IconMeta[] {
  return iconMetadata.filter((icon) => icon.category === category);
}

export function hasVariant(name: string, variant: IconVariant | string): boolean {
  return Boolean(metadataByName[name]?.variants.includes(variant as IconVariant));
}

export type { IconName, CategoryId };
`;

const aliasEntries: Record<string, string> = {};
for (const meta of iconMetadata) {
  aliasEntries[meta.name] = meta.name;
  for (const alias of meta.aliases) {
    aliasEntries[alias] = meta.name;
  }
}

const aliasContent = `
import type { IconName } from './types';

export const aliasMap: Record<string, IconName> = ${JSON.stringify(aliasEntries, null, 2)};

export function resolveIconName(name: string): IconName | undefined {
  return aliasMap[name] as IconName | undefined;
}
`;

const searchEntries = iconMetadata.map((meta) => ({
  name: meta.name,
  text: [meta.name, meta.category, ...meta.tags, ...meta.aliases]
    .join(' ')
    .toLowerCase(),
}));

const searchContent = `
import type { IconName } from './types';

export const searchIndex: Array<{ name: IconName; text: string }> = ${JSON.stringify(searchEntries, null, 2)};

export function searchIcons(query: string): IconName[] {
  const normalized = query.toLowerCase().trim();
  if (!normalized) {
    return searchIndex.map((entry) => entry.name);
  }
  return searchIndex
    .filter((entry) => entry.text.includes(normalized))
    .map((entry) => entry.name);
}
`;

writeGeneratedFile(path.join(ICONS_CORE_SRC, 'metadata.ts'), metadataContent);
writeGeneratedFile(path.join(ICONS_CORE_SRC, 'alias-map.ts'), aliasContent);
writeGeneratedFile(path.join(ICONS_CORE_SRC, 'search-index.ts'), searchContent);

const typesPath = path.join(ICONS_CORE_SRC, 'types.ts');
const typesSource = fs.readFileSync(typesPath, 'utf8');
const unionBlock = `// <AUTO-GENERATED:UNIONS>\nexport type IconName = ${iconNames.map((name) => `'${name}'`).join(' | ')};\nexport type CategoryId = ${categoryIds.map((id) => `'${id}'`).join(' | ')};\n// </AUTO-GENERATED:UNIONS>`;

const updatedTypes = typesSource.replace(
  /\/\/ <AUTO-GENERATED:UNIONS>[\s\S]*?\/\/ <\/AUTO-GENERATED:UNIONS>/,
  unionBlock,
);

fs.writeFileSync(typesPath, updatedTypes, 'utf8');
console.log(`Generated metadata for ${iconNames.length} icons.`);
